services:
  rf-sense:
    image: ghcr.io/guy16510/esp-rf-sense:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
      - "5566:5566/udp"
    environment:
      RF_SENSE_REQUIRED_NODES: "4"
      RF_SENSE_MIN_FRAME_RATE: "5"
      RF_SENSE_AUTO_LOAD_MODEL: "true"
      RF_SENSE_SLOT_A: "2f4b47f0"
      RF_SENSE_SLOT_B: "2f4b5390"
      RF_SENSE_SLOT_C: "2f4b735c"
      RF_SENSE_SLOT_D: "2f77883c"
    volumes:
      - ./data:/data
